import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar';
import Footer from './components/Footer';
const inter = Inter({ subsets: ['latin'] });
import { Metadata } from 'next';
import Banner from './components/Banner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-500">
        <Navbar />
        <Banner />
        {children}
        <Footer />
      </body>
    </html>
  );
}
